### ISSUE TITLE
plugin.dll missing

### ISSUE THREAD

**Issue by odahan** [dotinspace/Fundamental#1]
Hi, 
plugin.dll file is missing in latest release, there is only the plugin.dylib and the res folder :-(
Thanks for your help in advance.

**Comment by dotinspace** [comment]
Sorry, I just made a release quickly for Mac, and this is not my work, just a fork. Check out the original repo from MrLumps instead. Sorry about any inconvenience.

**Comment by odahan** [comment]
No problem, thanks for your answer !
