### ISSUE TITLE
makefile not working in osx?

### ISSUE THREAD

**Issue by OznipSlaugh** [dotinspace/Fundamental#2]
IMakefile:4: ../../plugin.mk: No such file or directory
make: *** No rule to make target `../../plugin.mk'.  Stop.

Apologies if this is an error on my side, not sure what's going wrong.
Thanks in advance for any reply.

**Comment by dotinspace** [comment]
Have you made sure that you are building from the right folder? As in the plugin folder of the rack repo? You need this to be able to build it.

**Comment by OznipSlaugh** [comment]
yep, Documents/Rack/plugins/vcv-MrLumps-master 

$make 

First I thought it was because the cp files seemed to be missing, nwo I'm not sure

Thank you for getting back!

**Comment by lnikj** [comment]
I think you are building in a binary version of Rack. You need to build the source version first and build MrLumps in its plugin directory.

**Comment by OznipSlaugh** [comment]
okay, I'll try that, thank you!
