### ISSUE TITLE
No Windows Binaries!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

### ISSUE THREAD

**Issue by rHutter** [dotinspace/Fundamental#3]
No Windows Binaries!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by Frizi** [comment]
This is open source, be polite and feel free to open a pull request if you miss something.

**Comment by dotinspace** [comment]
Sorry, I don't use Windows.
